CREATE DATABASE QL_GARA
GO
USE QL_GARA
GO
CREATE TABLE TAIKHOAN
(
MATK CHAR(10) PRIMARY KEY,
TENDN CHAR(10),
MATKHAU CHAR(10),
NGAYTAO DATETIME ,
)
GO
CREATE TABLE NHANVIEN 
(
MANV CHAR(10) PRIMARY KEY,
MATK CHAR(10) REFERENCES TAIKHOAN(MATK),
HOTEN NVARCHAR(10),
GIOITINH CHAR(3),
NGAYSINH DATETIME,
SDT CHAR(12),
CMND CHAR(10),
DIACHI NVARCHAR(20)
)
GO
CREATE TABLE BAOCAOTHANG
(
MABCT CHAR(10) PRIMARY KEY,
DOANHTHU MONEY ,
NGAYLAP DATETIME
)
GO
CREATE TABLE KHACHHANG
(
MAKH CHAR(10)PRIMARY KEY,
HOTEN NVARCHAR(10),
GIOITINH CHAR(3),
NGAYSINH DATETIME,
SDT CHAR(12),
CMND CHAR(10),
DIACHI NVARCHAR(20),
BIENSO CHAR(10),
LOAIXE CHAR(10)
)
GO
CREATE TABLE PHIEUTHUTIEN 
(
MAPTT CHAR(10) PRIMARY KEY,
MABCT CHAR(10) REFERENCES BAOCAOTHANG(MABCT),
MAKH CHAR(10) REFERENCES KHACHHANG(MAKH),
NGAYTHU DATETIME,
TIENTHU MONEY
)
GO
CREATE TABLE PHIEUSUACHUA
(
MAPSC CHAR(10) PRIMARY KEY,
MANV CHAR(10) REFERENCES NHANVIEN(MANV),
MAKH CHAR(10) REFERENCES KHACHHANG(MAKH),
NGAYSUACHUA DATETIME,
THANHTIEN MONEY
)
GO
CREATE TABLE PHUTUNG 
(
MAPT CHAR(10)PRIMARY KEY,
MABCT CHAR(10) REFERENCES BAOCAOTHANG(MABCT),
TENPT NVARCHAR(20),
DONGGIA MONEY ,
SOLUONG INT
)
GO
CREATE TABLE THONGTINSUACHUA
(
MAPT CHAR(10) REFERENCES PHUTUNG(MAPT),
MAPSC CHAR(10)REFERENCES PHIEUSUACHUA(MAPSC),
LOAISUACHUA INT ,
MOTA NVARCHAR(20),
SLPT_SUDUNG INT,
CHIPHI MONEY,
PRIMARY KEY(MAPT,MAPSC)
)
--DROP DATABASE QL_GARA